<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Admin_model');
        $this->load->library('form_validation');
    } 

    /*
     * Listing of admin
     */

    public function get_userdata(){
        $userData = $this->session->userdata();
        return $userData;
    }

    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('admin/index?');
        $config['total_rows'] = $this->Admin_model->get_all_admin_count();
        $this->pagination->initialize($config);

        //$data['user'] = $this->Admin_model->get_user_details($id_admin);
        $userData = $this->get_userdata();

        $data['admin'] = $this->Admin_model->get_all_admin($params);
        //$data['username'] = $this->Admin_model->get_username();
        
        $data['_view'] = 'admin/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new admin
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'username' => $this->input->post('username'),
            );
            
            $admin_id = $this->Admin_model->add_admin($params);
            redirect('admin/index');
        }
        else
        {            
            $data['_view'] = 'admin/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a admin
     */
    function edit($id_admin)
    {   
        // check if the admin exists before trying to edit it
        $data['admin'] = $this->Admin_model->get_admin($id_admin);
        
        if(isset($data['admin']['id_admin']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'username' => $this->input->post('username'),
                );

                $this->Admin_model->update_admin($id_admin,$params);            
                redirect('admin/index');
            }
            else
            {
                $data['_view'] = 'admin/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The admin you are trying to edit does not exist.');
    } 

    /*
     * Deleting admin
     */
    function remove($id_admin)
    {
        $admin = $this->Admin_model->get_admin($id_admin);

        // check if the admin exists before trying to delete it
        if(isset($admin['id_admin']))
        {
            $this->Admin_model->delete_admin($id_admin);
            redirect('admin/index');
        }
        else
            show_error('The admin you are trying to delete does not exist.');
    }

    function login(){
        $this->load->view('login/login');
    }



    public function cek_login(){
        //Untuk validasi username dan password
        $this->form_validation->set_rules('username', 'Username', 'required|min_length[5]',
                array(
                    'required' => "Username tidak boleh kosong"
                ));
        $this->form_validation->set_rules('password', 'Password', 'required|min_length[5]',
                array(
                    'required' => "Password tidak boleh kosong"
                ));
        if ($this->form_validation->run() == FALSE) {
            $this->load->view('login/login');
        } else {
            $data['login'] = $this->Admin_model->cek_data_login();
        }
    }

    public function logout(){
        $this->session->sess_destroy();
        redirect('Admin/login','refresh');
    }
    
}
