<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jemaat extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jemaat_model');
    } 

    /*
     * Listing of jemaat
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('jemaat/index?');
        $config['total_rows'] = $this->Jemaat_model->get_all_jemaat_count();
        $this->pagination->initialize($config);

        $data['jemaat'] = $this->Jemaat_model->get_all_jemaat($params);
        
        $data['_view'] = 'jemaat/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new jemaat
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('email','Email','valid_email');
		$this->form_validation->set_rules('status','Status','required');
		$this->form_validation->set_rules('status_jemaat','Status Jemaat','required');
		$this->form_validation->set_rules('id_admin','Id Admin','required');
		$this->form_validation->set_rules('jenis_kelamin','Jenis Kelamin','required');
		$this->form_validation->set_rules('password','Password','required');
		$this->form_validation->set_rules('ktp_sim','Ktp Sim','required');
		$this->form_validation->set_rules('kk','Kk','required');
		$this->form_validation->set_rules('nama_jemaat','Nama Jemaat','required');
		$this->form_validation->set_rules('username','Username','required');
		$this->form_validation->set_rules('tanggal_lahir','Tanggal Lahir','required');
		$this->form_validation->set_rules('alamat','Alamat','required');
		$this->form_validation->set_rules('umur','Umur','required');
		$this->form_validation->set_rules('pekerjaan','Pekerjaan','required');
		$this->form_validation->set_rules('nomer_telfon','Nomer Telfon','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'status' => $this->input->post('status'),
				'status_jemaat' => $this->input->post('status_jemaat'),
				'id_admin' => $this->input->post('id_admin'),
				'jenis_kelamin' => $this->input->post('jenis_kelamin'),
				'password' => $this->input->post('password'),
				'ktp_sim' => $this->input->post('ktp_sim'),
				'kk' => $this->input->post('kk'),
				'pengingat' => $this->input->post('pengingat'),
				'nama_jemaat' => $this->input->post('nama_jemaat'),
				'username' => $this->input->post('username'),
				'tanggal_lahir' => $this->input->post('tanggal_lahir'),
				'alamat' => $this->input->post('alamat'),
				'gereja_asal' => $this->input->post('gereja_asal'),
				'umur' => $this->input->post('umur'),
				'pekerjaan' => $this->input->post('pekerjaan'),
				'nomer_telfon' => $this->input->post('nomer_telfon'),
				'email' => $this->input->post('email'),
            );
            
            $jemaat_id = $this->Jemaat_model->add_jemaat($params);
            redirect('jemaat/index');
        }
        else
        {
			$this->load->model('Admin_model');
			$data['all_admin'] = $this->Admin_model->get_all_admin();
            
            $data['_view'] = 'jemaat/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a jemaat
     */
    function edit($id_jemaat)
    {   
        // check if the jemaat exists before trying to edit it
        $data['jemaat'] = $this->Jemaat_model->get_jemaat($id_jemaat);
        
        if(isset($data['jemaat']['id_jemaat']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('email','Email','valid_email');
			$this->form_validation->set_rules('status','Status','required');
			$this->form_validation->set_rules('status_jemaat','Status Jemaat','required');
			$this->form_validation->set_rules('id_admin','Id Admin','required');
			$this->form_validation->set_rules('jenis_kelamin','Jenis Kelamin','required');
			$this->form_validation->set_rules('password','Password','required');
			$this->form_validation->set_rules('ktp_sim','Ktp Sim','required');
			$this->form_validation->set_rules('kk','Kk','required');
			$this->form_validation->set_rules('nama_jemaat','Nama Jemaat','required');
			$this->form_validation->set_rules('username','Username','required');
			$this->form_validation->set_rules('tanggal_lahir','Tanggal Lahir','required');
			$this->form_validation->set_rules('alamat','Alamat','required');
			$this->form_validation->set_rules('umur','Umur','required');
			$this->form_validation->set_rules('pekerjaan','Pekerjaan','required');
			$this->form_validation->set_rules('nomer_telfon','Nomer Telfon','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'status' => $this->input->post('status'),
					'status_jemaat' => $this->input->post('status_jemaat'),
					'id_admin' => $this->input->post('id_admin'),
					'jenis_kelamin' => $this->input->post('jenis_kelamin'),
					'password' => $this->input->post('password'),
					'ktp_sim' => $this->input->post('ktp_sim'),
					'kk' => $this->input->post('kk'),
					'pengingat' => $this->input->post('pengingat'),
					'nama_jemaat' => $this->input->post('nama_jemaat'),
					'username' => $this->input->post('username'),
					'tanggal_lahir' => $this->input->post('tanggal_lahir'),
					'alamat' => $this->input->post('alamat'),
					'gereja_asal' => $this->input->post('gereja_asal'),
					'umur' => $this->input->post('umur'),
					'pekerjaan' => $this->input->post('pekerjaan'),
					'nomer_telfon' => $this->input->post('nomer_telfon'),
					'email' => $this->input->post('email'),
                );

                $this->Jemaat_model->update_jemaat($id_jemaat,$params);            
                redirect('jemaat/index');
            }
            else
            {
				$this->load->model('Admin_model');
				$data['all_admin'] = $this->Admin_model->get_all_admin();

                $data['_view'] = 'jemaat/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The jemaat you are trying to edit does not exist.');
    } 

    /*
     * Deleting jemaat
     */
    function remove($id_jemaat)
    {
        $jemaat = $this->Jemaat_model->get_jemaat($id_jemaat);

        // check if the jemaat exists before trying to delete it
        if(isset($jemaat['id_jemaat']))
        {
            $this->Jemaat_model->delete_jemaat($id_jemaat);
            redirect('jemaat/index');
        }
        else
            show_error('The jemaat you are trying to delete does not exist.');
    }
    
}
