<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kegiatan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kegiatan_model');

        if(!$this->session->userdata('logged_in')){
            redirect('Admin/login');
        }

        $id_admin = $this->session->userdata('username');
    } 

    /*
     * Listing of kegiatan
     */
    function index()
    {
        $data['kegiatan'] = $this->Kegiatan_model->get_all_kegiatan();
        
        $data['_view'] = 'kegiatan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new kegiatan
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('status','Status','required');
		$this->form_validation->set_rules('nama_kegiatan','Nama Kegiatan','required|max_length[255]');
		$this->form_validation->set_rules('waktu_kegiatan','Waktu Kegiatan','required');
		$this->form_validation->set_rules('tempat_kegiatan','Tempat Kegiatan','required|max_length[255]');
		$this->form_validation->set_rules('contact_person','Contact Person','required|max_length[255]');
		$this->form_validation->set_rules('pamflet','Pamflet','required|max_length[255]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_admin' => $this->input->post('id_admin'),
				'status' => $this->input->post('status'),
				'nama_kegiatan' => $this->input->post('nama_kegiatan'),
				'waktu_kegiatan' => $this->input->post('waktu_kegiatan'),
				'tempat_kegiatan' => $this->input->post('tempat_kegiatan'),
				'contact_person' => $this->input->post('contact_person'),
				'pamflet' => $this->input->post('pamflet'),
            );
            
            $kegiatan_id = $this->Kegiatan_model->add_kegiatan($params);
            redirect('kegiatan/index');
        }
        else
        {
			$this->load->model('Admin_model');
			$data['all_admin'] = $this->Admin_model->get_all_admin();
            
            $data['_view'] = 'kegiatan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a kegiatan
     */
    function edit($id_kegiatan)
    {   
        // check if the kegiatan exists before trying to edit it
        $data['kegiatan'] = $this->Kegiatan_model->get_kegiatan($id_kegiatan);
        
        if(isset($data['kegiatan']['id_kegiatan']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('status','Status','required');
			$this->form_validation->set_rules('nama_kegiatan','Nama Kegiatan','required|max_length[255]');
			$this->form_validation->set_rules('waktu_kegiatan','Waktu Kegiatan','required');
			$this->form_validation->set_rules('tempat_kegiatan','Tempat Kegiatan','required|max_length[255]');
			$this->form_validation->set_rules('contact_person','Contact Person','required|max_length[255]');
			$this->form_validation->set_rules('pamflet','Pamflet','required|max_length[255]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_admin' => $this->input->post('id_admin'),
					'status' => $this->input->post('status'),
					'nama_kegiatan' => $this->input->post('nama_kegiatan'),
					'waktu_kegiatan' => $this->input->post('waktu_kegiatan'),
					'tempat_kegiatan' => $this->input->post('tempat_kegiatan'),
					'contact_person' => $this->input->post('contact_person'),
					'pamflet' => $this->input->post('pamflet'),
                );

                $this->Kegiatan_model->update_kegiatan($id_kegiatan,$params);            
                redirect('kegiatan/index');
            }
            else
            {
				$this->load->model('Admin_model');
				$data['all_admin'] = $this->Admin_model->get_all_admin();

                $data['_view'] = 'kegiatan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The kegiatan you are trying to edit does not exist.');
    } 

    /*
     * Deleting kegiatan
     */
    function remove($id_kegiatan)
    {
        $kegiatan = $this->Kegiatan_model->get_kegiatan($id_kegiatan);

        // check if the kegiatan exists before trying to delete it
        if(isset($kegiatan['id_kegiatan']))
        {
            $this->Kegiatan_model->delete_kegiatan($id_kegiatan);
            redirect('kegiatan/index');
        }
        else
            show_error('The kegiatan you are trying to delete does not exist.');
    }
    
}
