<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get admin by id_admin
     */
    function get_admin($id_admin)
    {
        return $this->db->get_where('admin',array('id_admin'=>$id_admin))->row_array();
    }
    
    /*
     * Get all admin count
     */
    function get_all_admin_count()
    {
        $this->db->from('admin');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all admin
     */
    function get_all_admin($params = array())
    {
        $this->db->order_by('id_admin', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('admin')->result_array();
    }
        
    /*
     * function to add new admin
     */
    function add_admin($params)
    {
        $this->db->insert('admin',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update admin
     */
    function update_admin($id_admin,$params)
    {
        $this->db->where('id_admin',$id_admin);
        return $this->db->update('admin',$params);
    }
    
    /*
     * function to delete admin
     */
    function delete_admin($id_admin)
    {
        return $this->db->delete('admin',array('id_admin'=>$id_admin));
    }

    function logged_id()
    {
        return $this->session->userdata('id_admin');
    }

    public function login_user($username, $password){
        $this->db->where('username', $username);
        $this->db->where('password', $password);

        $result = $this->db->get('admin');
        
        if($result->num_rows() == 1){
            return $result->row(0)->id_admin;
        } else {
            return false;
        }
    }

    public function get_user_details($username)
    {
       $result = $this->db->get('admin');

       if ($result->num_rows() == 1) {
           return $result->row();
       } else {
           return false;
       }
   }
}
