<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kegiatan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kegiatan by id_kegiatan
     */
    function get_kegiatan($id_kegiatan)
    {
        return $this->db->get_where('kegiatan',array('id_kegiatan'=>$id_kegiatan))->row_array();
    }
    
    /*
     * Get all kegiatan count
     */
    function get_all_kegiatan_count()
    {
        $this->db->from('kegiatan');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all kegiatan
     */
    function get_all_kegiatan()
    {
        return $this->db->get('kegiatan')->result_array();
    }
        
    /*
     * function to add new kegiatan
     */
    function add_kegiatan($params)
    {
        $this->db->insert('kegiatan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kegiatan
     */
    function update_kegiatan($id_kegiatan,$params)
    {
        $this->db->where('id_kegiatan',$id_kegiatan);
        return $this->db->update('kegiatan',$params);
    }
    
    /*
     * function to delete kegiatan
     */
    function delete_kegiatan($id_kegiatan)
    {
        return $this->db->delete('kegiatan',array('id_kegiatan'=>$id_kegiatan));
    }

    // private function _uploadImage()
    // {
    //     $config['upload_path']          = './upload/product/';
    //     $config['allowed_types']        = 'gif|jpg|png';
    //     $config['file_name']            = $this->product_id;
    //     $config['overwrite']            = true;
    //     $config['max_size']             = 1024; // 1MB
    // // $config['max_width']            = 1024;
    // // $config['max_height']           = 768;

    // $this->load->library('upload', $config);

    // if ($this->upload->do_upload('image')) {
    //     return $this->upload->data("file_name");
    // }
    
    // return "default.jpg";
    // }
}
